### PR TITLE
Updated the typo in polars_parser.py

### PR DESCRIPTION
**Pull request by vignesh1507**
The property dataset_tpye is misspelled. It should be dataset_type.

Fixed code snippet:

`@property
def dataset_type(self) -> str:
    return "polars_dataframe"
`

### CODE REVIEW

**Comment by longxiaofei** [comment]
Not only `pandas_parser.py`,  you can search globally for "dataset_tpye", and typo these.

**Comment by vignesh1507** [comment]
I've searched globally and i didn't find any typo same as `dataset_tpye`.

**Comment by longxiaofei** [comment]
I found 9 cases.

image

**Comment by longxiaofei** [comment]
open new pr to typo: https://github.com/Kanaries/pygwalker/pull/643

**Pull request closed without merging**
